In [1]:
import pandas as pd

In [2]:
titanic_df = pd.read_csv(r'C:\Users\pinki\Documents\titanic_train.csv')

In [3]:
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [4]:
print('titanic 변수 type :', type(titanic_df))

titanic 변수 type : <class 'pandas.core.frame.DataFrame'>


In [5]:
#모든 dataframe 내의 데이터는 생성되는 순간 고유의 index값을 가진다.

In [6]:
#행과 열 크기를 알아보는 법
print('dataframe 크기:', titanic_df.shape)

dataframe 크기: (891, 12)


In [7]:
#dataframe은 데이터 뿐만이 아닌 칼럼의 타입, null 데이터 개수, 데이터 분포도 등의 메타 데이터도 조회할수 있음.
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [10]:
#age는 891개 중에서 714개가 non-null이기 때문에 나머지는 null값
# float64 2개, int64 5개 object 5개
#describe() 숫자형 데이터 값의 n-percentile분포도, 평균값, 최댓값, 최솟값 나타냄
#describe만 적으면 5개의 모든 값들을 보여준다.
titanic_df.describe

<bound method NDFrame.describe of      PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                 

In [11]:
titanic_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [12]:
#describe() 해당 숫자 칼럼이 숫자형 카테고리 칼럼인지를 판단할 수 있게 도와줌 ex) 남자를 1 여자를 2
#passengerID 는 1~891 숫자가 할당 돼있음 => 의미있는 분석 X
#Survived => 0,1로 이루어진 카테고리 칼럼, Pclass => 1,2,3으로 나눠진 카테고리 칼럼
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)

Pclass
3    491
1    216
2    184
Name: count, dtype: int64


In [13]:
# Series는 index와 단 하나의 칼럼으로 구서오딘 데이터 세트
titanic_pclass = titanic_df['Pclass']
print(type(titanic_pclass))

<class 'pandas.core.series.Series'>


In [15]:
# 모든 dataframe과 Series는 index를 가진다.
titanic_pclass.head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [16]:
print(type(value_counts))

<class 'pandas.core.series.Series'>


In [18]:
#고유성이 보장된다면 의미 있는 데이터값 할당도 가능함.
print(value_counts)

Pclass
3    491
1    216
2    184
Name: count, dtype: int64


In [19]:
#value_counts()메서드는 null값을 무시함. => dropna인자로 판단함
print('titanic_df 데이터 건수:', titanic_df.shape[0])
print('기본설정인 dropna = True로 value_counts()')
#value_counts()는 디포트로 dropna = True이므로 value_counts(dropna = True)와 동일
print(titanic_df['Embarked'].value_counts())
print(titanic_df['Embarked'].value_counts(dropna = False))

titanic_df 데이터 건수: 891
기본설정인 dropna = True로 value_counts()
Embarked
S    644
C    168
Q     77
Name: count, dtype: int64
Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64


In [20]:
#Dataframe은 파이썬의 리스트, 딕셔너리, 넘파이ndarray등으로 변환 가능
import numpy as np

In [21]:
col_name1 = ['col']
list1 = [1,2,3]
array1 = np.array(list1)
print('array1 shape:', array1.shape)

#리스트를 이용해 DataFrame생성
df_list1 = pd.DataFrame(list1, columns = col_name1)
print('1차원으로 만든DataFrame:\n', df_list1)

#넘파이 ndarray를 이용해 DataFrame생성
df_array1 = pd.DataFrame(array1, columns = col_name1)
print('1차원 ndarray로 만든 DataFrame:\n', df_array1)

array1 shape: (3,)
1차원으로 만든DataFrame:
    col
0    1
1    2
2    3
1차원 ndarray로 만든 DataFrame:
    col
0    1
1    2
2    3


In [22]:
col_name2 = ['col1','col2','col3']

list2 = [[1,2,3],[11,12,13]]
array2 = np.array(list2)
print('array2 shape:', array2.shape)

df_list2 = pd.DataFrame(list2, columns = col_name2)
print('리스트로 만든 df:/n', df_list2)

df_array2 = pd.DataFrame(array2, columns = col_name2)
print('array로 만든 df:\n', df_array2)

array2 shape: (2, 3)
리스트로 만든 df:/n    col1  col2  col3
0     1     2     3
1    11    12    13
array로 만든 df:
    col1  col2  col3
0     1     2     3
1    11    12    13


In [27]:
#dict는 dataframe형태로 변환하면 ,key값은 칼럼명, value값은 칼럼데이터로 매핑된다.
dict = {'col1':[1,11],'col2':[2,22],'col3':[3,33]}
df_dict = pd.DataFrame(dict)
print(df_dict)

   col1  col2  col3
0     1     2     3
1    11    22    33


In [28]:
array3 = df_dict.values
print(array3)
#dataframe에서 array로 변환하는법은 values

[[ 1  2  3]
 [11 22 33]]


In [29]:
list3 = df_dict.values.tolist()
print('타입', type(list3))

타입 <class 'list'>


In [34]:
dict3 = df_dict.to_dict('list')
print('타입', type(dict))

타입 <class 'dict'>


In [35]:
print(dict3,'\n')
print(list3)

{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]} 

[[1, 2, 3], [11, 22, 33]]


In [38]:
#칼럼데이터 세트 생성과 수정
titanic_df['Age_0'] = 0
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  
0      0         A/5 21171   7.2500   NaN        S      0  
1      0          PC 17599  71.2833   C85        C      0  
2      0  STON/O2. 3101282   7.9250   NaN        S      0

In [41]:
titanic_df['Age_by_10'] = titanic_df['Age']*10
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch']+1
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0      0         A/5 21171   7.2500   NaN        S      0      220.0   
1      0          PC 17599  71.2833   C85        C      0      380.0   
2      0  STON/O2. 3101282   7.9250   NaN        S      0      260.0   

   Family_No  
0          2  
1          2  
2          1

In [44]:
titanic_df['Age_by_10'] = titanic_df['Age_by_10'] - 100
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0      0         A/5 21171   7.2500   NaN        S      0      320.0   
1      0          PC 17599  71.2833   C85        C      0      480.0   
2      0  STON/O2. 3101282   7.9250   NaN        S      0      360.0   

   Family_No  
0          2  
1          2  
2          1

In [46]:
#dataframe 데이터 삭제
#DataFrame.drop의 원현 => DataFrame.drop(labels = None, axis = 0, index = None, columns = Npne, level = None, inplace = False, errors='raise')
# 중요한 파라미터는 labels, axis, inplace
#axis 0 은 로우방향 => 가로 드랍, axis 1은 칼럼 방향 => 세로 드랍
#labels에 원하는 칼럼명을 입력함

titanic_drop_df = titanic_df.drop('Age_0', axis = 1)
titanic_drop_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_by_10  Family_No  
0      0         A/5 21171   7.2500   NaN        S      320.0          2  
1      0          PC 17599  71.2833   C85        C      480.0          2  
2      0  STON/O2. 3101282   7.9250   NaN        S      360.0          1

In [47]:
#inpalce = Flase이면 자기자신의 dataframe의 데이터는 삭제하지 않고, 삭제된 결과를 반환함
drop_result = titanic_df.drop(['Age_0', 'Age_by_10', 'Family_No'], axis = 1, inplace = True)
print(drop_result)
titanic_df.head(3)
#inplace=True면 반환값이 None이 된다.

None


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [48]:
print(titanic_drop_df)

     PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ... 

In [50]:

print('#### before axis 0 drop ####')
print(titanic_df.head(3))
print('#### after axis drop ####')
titanic_df.drop([0,1,2],axis = 0, inplace = True)
print(titanic_df.head(3))

#### before axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
#### after axis drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q


In [52]:
titanic_df = pd.read_csv(r'C:\Users\pinki\Documents\titanic_train.csv')

In [53]:
indexes = titanic_df.index
print(indexes)

RangeIndex(start=0, stop=891, step=1)


In [54]:
print('Index 객체 array값:\n',indexes.values)

Index 객체 array값:
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 

In [55]:
print(type(indexes.values))
print(indexes.values.shape)
print(indexes.values[:5])
print(indexes[:5].values)
print(indexes[6])

<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6


In [57]:
#index값은 변경 불가능
indexes[0] = 5

TypeError: Index does not support mutable operations

In [58]:
series_fair = titanic_df['Fare']
print('Fair Series max 값:', series_fair.max())
print('Fair Series sum 값:', series_fair.sum())
print('sum() Fair Series:', sum(series_fair))
print('Fair Series + 3:\n', (series_fair +3).head(3))
print(series_fair.head(3))

Fair Series max 값: 512.3292
Fair Series sum 값: 28693.9493
sum() Fair Series: 28693.9493
Fair Series + 3:
 0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64
0     7.2500
1    71.2833
2     7.9250
Name: Fare, dtype: float64


In [59]:
titanic_reset_df = titanic_df.reset_index(inplace = False)
titanic_reset_df.head(3)

index  PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0      0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1      1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2      2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

In [64]:
print(value_counts)

Pclass
3    491
1    216
2    184
Name: count, dtype: int64


In [65]:
value_counts.reset_index()
#drop을 True로 설정하면 기존 인덱스는 새로운 칼럼으로 추가되지 않고 삭제됨.

Pclass  count
0       3    491
1       1    216
2       2    184

In [66]:
print(titanic_df['Pclass'].head(3))

0    3
1    1
2    3
Name: Pclass, dtype: int64


In [67]:
print(titanic_df[['Pclass','Survived']].head(3))

   Pclass  Survived
0       3         0
1       1         1
2       3         1


In [68]:
titanic_df[0:2]

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0  A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0   PC 17599  71.2833   C85        C

In [69]:
titanic_df[0]

KeyError: 0

In [71]:
titanic_df[titanic_df['Pclass'] == 3].head(3)
#dataframe[]내 입력값은 칼럼명 혹은 불린 인덱스 용도로만 사용해야함.

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket   Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171  7.250   NaN        S
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...  7.925   NaN        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0          373450  8.050   NaN        S

In [72]:
data = {'Name': ['Chulmin','Eunkyung','Jinwoong','Sooboem'],
        'Year': [2011, 2016, 2015, 2015],
        'Gender': ['Male', 'Female', 'Male','Female']
       }
data_df = pd.DataFrame(data, index = ['one','two','three', 'four'])
data_df

Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Sooboem  2015  Female

In [74]:
#iloc[,] => 행과 열 위치
data_df.iloc[0,0]

'Chulmin'

In [76]:
print(data_df.iloc[1,0])
print(data_df.iloc[2,1])
#여러개 부터는 dataframe반환
print(data_df.iloc[0:2, [0,1]])
print(data_df.iloc[0:2, 0:3])
print(data_df.iloc[:])
print(data_df.iloc[:,:])

Eunkyung
2015
         Name  Year
one   Chulmin  2011
two  Eunkyung  2016
         Name  Year  Gender
one   Chulmin  2011    Male
two  Eunkyung  2016  Female
           Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Sooboem  2015  Female
           Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Sooboem  2015  Female


In [77]:
type(data_df.iloc[1,0])

str

In [78]:
type(data_df.iloc[0:2, [0,1]])

pandas.core.frame.DataFrame

In [79]:
#loc은 명칭 기반으로 데이터 추출함
data_df.loc['one','Name']

'Chulmin'

In [80]:
data_df.loc['one':'three','Name']

one       Chulmin
two      Eunkyung
three    Jinwoong
Name: Name, dtype: object